#!/bin/bash
# Copyright (C) Metaswitch Networks 2017
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

set -ue

USAGE="Usage: cw-check_cluster_state"
local_site_name=site1
site_names=
. /etc/clearwater/config

if [ $# -ne 0 ]
then
  if [ "$1" == -h ] || [ "$1" == --help ]
  then
    echo $USAGE
    exit 0
  else
    echo $USAGE
    exit 1
  fi
fi

/usr/share/clearwater/clearwater-cluster-manager/env/bin/python /usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py "${management_local_ip:-$local_ip}" "$local_ip" "$local_site_name" "$site_names"
exit $?