#!/bin/bash

# Copyright (C) Metaswitch Networks 2016
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.
if [[ -z $1 ]]; then
  echo "You must provide a location to restore the configuration from" >&2
  echo >&2
  echo "Usage: $0 backup_directory" >&2
  exit 1
fi

# make sure the provided path exists and is a directory
if [[ ! -d $1 ]]; then
  echo "The provided location '$1' is not a directory" >&2
  echo >&2
  echo "Usage: $0 backup_directory" >&2
  exit 1
fi

local_site_name=site1
etcd_key=clearwater
. /etc/clearwater/config

backup_directory="$1"

top_key=${etcd_key}/${local_site_name}/configuration

# Check we can contact `etcd`
if ! nc -z ${management_local_ip:-$local_ip} 4000
then
  echo "Unable to contact etcd at ${management_local_ip:-$local_ip} on port 4000" >&2
  exit 2
fi

# Set null globbing so thatif there are no files in the directory,
# we don't attempt to upload a file named *.
shopt -s nullglob

FILES=("$backup_directory"/*)

# The backup directory should contain some files, otherwise there is nothing
# to restore.
if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "No available configuration to restore in: $backup_directory " >&2
  exit 1
fi

tmp_backup_dir=$(mktemp -d /tmp/backup_XXXXX)
cw-backup_config $tmp_backup_dir

for filename in "${FILES[@]}"
do
  key=$(basename "$filename")
  if [[ -d $filename ]]; then
    echo "$key is a directory, it will not be uploaded"
    continue
  fi
  if [[ $key =~ " " ]]; then
    echo "$key contains a space in the filename, it will not be uploaded"
    continue
  fi
  if [ "$key" != "apply_config" ]; then
    if [[ ! -e $tmp_backup_dir/$key ]]; then
      # create an empty version of this file to compare against for logging
      touch "$tmp_backup_dir/$key"
    fi
    # Log all changes to syslog - compare to most recent version that we
    # downloaded to tmp_backup_dir
    /usr/share/clearwater/clearwater-config-manager/env/bin/print_diff_and_syslog --config_type "$key" --config_before "$tmp_backup_dir/$key" --config_after "$backup_directory/$key" > /dev/null

    # Upload the file to etcd
    keypath=http://${management_local_ip:-$local_ip}:4000/v2/keys/${top_key}/$key
    tmp_file=/tmp/restore-config.$key
    curl -X PUT $keypath --data-urlencode value@${f} 2> ${tmp_file}.stderr.$$ | tee ${tmp_file}.stdout.$$ | egrep -q "\"action\":\"set\""
    rc=$?

    # Check the return code and log if appropriate.
    if [ $rc != 0 ] ; then
      echo "Failed to upload key $key to etcd with return code $rc" >&2
      cat ${tmp_file}.stderr.$$              >&2
      cat ${tmp_file}.stdout.$$              >&2
      exit 3
    fi

    rm -f ${tmp_file}.stderr.$$ ${tmp_file}.stdout.$$
  fi
done

rm -rf $tmp_backup_dir

